# Generated by Django 4.2 on 2024-12-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="test@gmail.com", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="first", max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="last", max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="nick", max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="Anonymous", max_length=30, unique=True),
        ),
    ]
