# Generated by Django 4.2 on 2024-12-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="test@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="first", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="last", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="Anonymous", max_length=150, unique=True),
        ),
    ]
