# Generated by Django 4.2 on 2024-12-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_author_article_author_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="author",
        ),
    ]
