# Generated by Django 4.2 on 2024-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_author_id_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_nickname",
            field=models.CharField(default="Anonymous", max_length=30),
        ),
        migrations.AddField(
            model_name="comment",
            name="author_nickname",
            field=models.CharField(default="Anonymous", max_length=30),
        ),
    ]
