# Generated by Django 4.2 on 2024-12-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_article_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
