# Generated by Django 4.2 on 2024-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_article_likes_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="products.hashtag"
            ),
        ),
    ]
