# Generated by Django 4.2 on 2024-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_hashtag_article_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hashtags_input",
            field=models.TextField(blank=True),
        ),
    ]
