# Generated by Django 4.2 on 2024-12-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_article_hashtags_input"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="hashtags_input",
        ),
    ]
