# Generated by Django 4.2 on 2024-12-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_article_hashtags_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hashtags_input",
            field=models.TextField(blank=True),
        ),
    ]
